### Spring properties
# Service registers under this name
spring:
  application:
    name: restclient-service
    
    
 # Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
  # HTTP Server (Tomcat) Port
server: 
  port: 3333
  
     